import QtQml 2.12
import QtQml.Models 2.12
import QtQml.StateMachine 1.12
import QtQuick 2.12
import QtQuick.Extras 1.4
import QtQuick.Layouts 1.12
import QtQuick.Controls 1.6
import QtQuick.Controls.Styles 1.4
import QtQuick.Controls 2.12
import QtQuick.Controls.Imagine 2.12
import QtQuick.Controls.Material 2.12
import QtQuick.Controls.Fusion 2.12
import QtQuick.Controls.Universal 2.12
import QtQuick.Window 2.12
import QtQuick.Dialogs 1.3
import QtQuick.XmlListModel 2.12
import QtQuick.Templates 2.12
import QtQuick.Particles 2.12
import QtQuick.LocalStorage 2.12
import Qt.labs.platform 1.1
import Qt.labs.calendar 1.0
import Qt.labs.folderlistmodel 1.0
import Qt.labs.settings 1.1
import Qt.labs.qmlmodels 1.0
import Qt.labs.location 1.0
import Qt.labs.sharedimage 1.0
import Qt.labs.wavefrontmesh 1.12
import QtSensors 5.12
import QtPurchasing 1.12
import QtPositioning 5.12
import QtLocation 5.12
import QtNfc 5.12
import QtMultimedia 5.12
import QtGraphicalEffects 1.12
import QtDataVisualization 1.3
import QtBluetooth 5.12
import QtQuick.Shapes 1.12
import QtCharts 2.3
import QtGamepad 1.12
import QtAudioEngine 1.1
import QtScxml 5.8
import QtWebView 1.1
import QtWebChannel 1.0
import QtWebEngine 1.8
import QtWebSockets 1.1

Item {}
