import QtQuick 2.0
import QtQuick.Layouts 1.0
import QtQuick.Controls 1.0
import QtQuick.Window 2.0
import Qt.WebSockets 1.0
import QtQml 2.0
import QtQml.Models 2.1
import QtQuick.Dialogs 1.0
import QtQuick.Controls.Styles 1.0
import QtQuick.XmlListModel 2.0
import QtQuick.Templates 2.0
import QtQuick.Particles 2.0
import QtQuick.LocalStorage 2.0
import Qt.labs.calendar 1.0
import Qt.labs.folderlistmodel 1.0
import Qt.labs.gestures 1.0
import Qt.labs.particles 1.0
import Qt.labs.settings 1.0
import QtWebKit 3.0
import QtWebKit 1.0
import QtTest 1.0
import QtSensors 5.3
import QtPurchasing 1.0
import QtPositioning 5.0
import QtNfc 5.0
import QtMultimedia 5.0
import QtGraphicalEffects 1.0
import QtDataVisualization 1.0
import QtBluetooth 5.0
import QtWebView 1.1
import QtQuick.Extras 1.4
Item {}
